baseURL = "https://gross2001.github.io/tatlib/"
languageCode = 'en-us'
title = 'Tatarlib'
publishDir = "public"

theme = "ananke"

[taxonomies]
    author = 'authors'
    genre = 'genres'
    publisher = 'publisher'